### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by ramihemang90** [jogy/jmoney#3]
Firstly, I am not aware with gradle. I read couple of documents and tried my way. Basically, I am trying to create war but failed to do so. 

Using gradle I have created pom.xml file for maven. Getting following file while creating war file. Need correct pom.xml file to non gradle developers to build and continue.

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.h2database:h2:jar is missing. @ line 9, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jetty:jar is missing. @ line 14, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-data-rest:jar is missing. @ line 19, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 24, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-data-jpa:jar is missing. @ line 35, column 17
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @ line 40, column 17

**Comment by jogy** [comment]
Integrated with Travis CI
